// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PagoEfectivo.Api.Infra;

namespace PagoEfectivo.Api.Migrations
{
    [DbContext(typeof(PagoEfectivoContext))]
    partial class PagoEfectivoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("PagoEfectivo.Api.Domain.Model.Estado", b =>
                {
                    b.Property<int>("Id_Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Descripcion")
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id_Estado");

                    b.ToTable("Estado");

                    b.HasData(
                        new
                        {
                            Id_Estado = 1,
                            Descripcion = "GENERADO"
                        },
                        new
                        {
                            Id_Estado = 2,
                            Descripcion = "CANJEADO"
                        });
                });

            modelBuilder.Entity("PagoEfectivo.Api.Domain.Model.Promocion", b =>
                {
                    b.Property<Guid>("Id_Promocion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Id_Estado")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id_Promocion");

                    b.HasIndex("Id_Estado");

                    b.ToTable("Promocion");
                });

            modelBuilder.Entity("PagoEfectivo.Api.Domain.Model.Promocion", b =>
                {
                    b.HasOne("PagoEfectivo.Api.Domain.Model.Estado", "Estado")
                        .WithMany("Promocion")
                        .HasForeignKey("Id_Estado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("PagoEfectivo.Api.Domain.Model.Estado", b =>
                {
                    b.Navigation("Promocion");
                });
#pragma warning restore 612, 618
        }
    }
}
